-- Drop table
DROP TABLE IF EXISTS ACTIVITY cascade;
DROP TABLE IF EXISTS AUDIT cascade;
-- Create table
CREATE TABLE ACTIVITY
(
  ID        INT NOT NULL AUTO_INCREMENT,
  ACTIVITY  VARCHAR(255)   NOT NULL,
  DESCRIPTION    VARCHAR(255) NOT NULL,
  CONSTRAINT activity_pk PRIMARY KEY (id)
);

CREATE TABLE AUDIT_LOG
(
  ID        INT NOT NULL AUTO_INCREMENT,
  ACTIVITY_ID INT   NOT NULL,
  ACTIVITY VARCHAR(255) NOT NULL,
  IP_ADDRESS    VARCHAR(255) NOT NULL,
  USER_NAME VARCHAR(255) NOT NULL,
  CREATED_TIME DATE NOT NULL,
  CONSTRAINT audit_pk PRIMARY KEY (id),
  CONSTRAINT audit_activity_fk FOREIGN KEY (activity_id) REFERENCES activity (id)
);